### PR TITLE
Issue #12: If scanner is remote, use only scandata in testclient

### LINKED ISSUE #12: Indicate noteworthy SCANDATA vs SCANFILE result
I really like the test client to check if everything is working. But I have `antivirus_savdi | scannerisremote` enabled and wondered what is wrong here:
image
At least until I noticed that for `scannerisremote` only the SCANDATA result is noteworthy.

Probably I should just disable the SCANFILE feature on SAVDID. But I didn't and I was very confused :-). So it might be helpful to indicate which of SCANDATA/SCANFILE is actually the interesting one (depending on `scannerisremote`).

### PR DESCRIPTION
**Pull request by Peterburnett**
Closes #12

### CODE REVIEW

**Comment by brendanheywood** [comment]
As I've said internally the check api class needs a touchpoint too before this should land

**Comment by Peterburnett** [comment]
Thanks @brendanheywood I have added the Check API touch point

**Comment by Peterburnett** [comment]
Hi @jonof Are you able to review this patch at any point?

**Comment by jonof** [comment]
Now that I'm not on holidays anymore, I will.

**Pull request merged**
